version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GLEAM_VERSION: 1.6.2
    ports:
      - "8000:8000"
    environment:
      CLAMAV_HOSTNAME: clamav
      CLAMAV_PORT: 3310
    depends_on:
      - clamav

  clamav:
    image: clamav/clamav
    ports:
      - "3310:3310"
