version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GLEAM_VERSION: 1.6.2
    ports:
      - "8000:8000"

  clamav:
    image: clamav/clamav
    ports:
      - "3310:3310"